name: page285
favicon: null
layout_spectrum: 0.6187450236175209
typography_spectrum: 0.10410309094004333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7f5fe'
    - '#0e1211'
    - '#3c3733'
    - '#4d5e39'
    - '#8e8c91'
  brandStrength: 0.5
  lightness: 0.37496579834260046
  saturation: 0.8901015955489129
  rhythmicContrast: 0.28928208560682833
purpose: []
