name: page285
favicon: null
layout_spectrum: 0.6187450236175209
typography_spectrum: 0.10410309094004333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8209101846441627
  lightness: 0.37496579834260046
  saturation: 0.8901015955489129
  rhythmicContrast: 0.28928208560682833
purpose: []
